### ISSUE TITLE
https problem?

### ISSUE THREAD

**Issue by brainwane** [amiaopensource/ffmprovisr#18] opened 2015-12-02 20:09 UTC
In Firefox, when viewing https://amiaopensource.github.io/ffmprovisr/ (note the HTTPS), I get a mixed content error that stops the individual items from expanding when clicked on.

**Comment by ablwr** [comment] 2015-12-02 20:21
Sumana, thanks for this catch! Confirmed this is a problem in Chrome too. Due to my lazy copy-pasting of the dependent CDNs (several of which I'm interested in trying to move off of anyway and hosting in-repo for offline use). I'll fix this when I get a chance later tonight.

**Comment by retokromer** [comment] 2015-12-06 06:12
On Slackware 14.1 it says that the pop-up windows are not secure.
(And with w3m all the content of index.html, including all pop-up windows, is shown in one single window when using both http:// and https:// ;-)

**Comment by ablwr** [comment] 2015-12-07 01:58
An easy fix to a safer internet! https://github.com/amiaopensource/ffmprovisr/commit/5b01c17fa25509ba56a77817756085a55f5c321e resolves.

**Comment by retokromer** [comment] 2015-12-11 10:07
I guess it’s fine now, and I close this issue.

**Closed as completed by retokromer** 2015-12-11 10:07 UTC
